import { NextResponse } from 'next/server';
import { Model3D } from '@/domain/types';

export async function GET() {
  const models: Model3D[] = [
    {
      id: 'm1',
      name: 'Llavero Creamax',
      source: 'internal',
      fileUrl: '/models/llaveroCreamax.stl',
      overlayImageUrl: '/models/thumb-llavero.png',
      status: 'BORRADOR',
      createdAt: new Date().toISOString(),
      nfc: true,
      updatedAt: new Date().toISOString(),
      price: 15000,
      description: 'Llavero personalizado de Creamax',
    },
    {
      id: 'm2',
      name: 'Llavero Cafe',
      source: 'internal',
      fileUrl: '/models/llaveroCafe.stl',
      overlayImageUrl: '/models/thumb-llavero.png',
      status: 'BORRADOR',
      createdAt: new Date().toISOString(),
      nfc: false,
      updatedAt: new Date().toISOString(),
      price: 12000,
      description: 'Llavero con diseño de taza de café',
    },
    {
      id: 'm3',
      name: 'Llavero Freicars',
      source: 'internal',
      fileUrl: '/models/llaveroFreicars.stl',
      overlayImageUrl: '/models/thumb-llavero.png',
      status: 'BORRADOR',
      createdAt: new Date().toISOString(),
      nfc: false,
      updatedAt: new Date().toISOString(),
      price: 18000,
      description: 'Llavero con logo de Freicars',
    },
    {
      id: 'm4',
      name: 'Llavero Easy Tech',
      source: 'internal',
      fileUrl: '/models/llaveroEasyTech2.stl',
      overlayImageUrl: '/models/thumb-llavero.png',
      status: 'BORRADOR',
      createdAt: new Date().toISOString(),
      nfc: false,
      updatedAt: new Date().toISOString(),
      price: 20000,
      description: 'Llavero con diseño tecnológico de Easy Tech',
    },
    {
      id: 'm5',
      name: 'Llavero Valle del Lili',
      source: 'internal',
      fileUrl: '/models/llaveroValleLili.stl',
      overlayImageUrl: '/models/thumb-llavero.png',
      status: 'BORRADOR',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      nfc: true,
      price: 17000,
    },
    {
      id: 'm6',
      name: 'Llavero Corazon',
      source: 'internal',
      fileUrl: '/models/llaveroCorazon.stl',
      overlayImageUrl: '/models/thumb-llavero.png',
      status: 'BORRADOR',
      createdAt: new Date().toISOString(),
      nfc: false,
      price: 16000,
      description: 'Llavero con forma de corazón',
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'm7',
      name: 'Llavero Jabon Rey',
      source: 'internal',
      fileUrl: '/models/llaveroJabonRey.stl',
      overlayImageUrl: '/models/thumb-llavero.png',
      status: 'BORRADOR',
      createdAt: new Date().toISOString(),
      nfc: false,
      price: 14000,
      description: 'Llavero con diseño de Jabon Rey',
      updatedAt: new Date().toISOString(),
    },
  ];

  return NextResponse.json(models);
}
